api = 2
core = 7.x

# Override
projects[features][version] = "1.0-rc3"
projects[views][version] = "3.3"
projects[ctools][version] = "1.0"

;--------------------
; Additional Contrib
;--------------------

projects[ckeditor][version] = "1.9"
projects[ckeditor][subdir] = "contrib"

projects[entity][version] = "1.0-rc2"
projects[entity][subdir] = "contrib"

projects[entityreference][version] = "1.0-rc1"
projects[entityreference][subdir] = "contrib"

projects[entityconnect][version] = "1.0-alpha5"
projects[entityconnect][subdir] = "contrib"

projects[eva][version] = "1.1"
projects[eva][subdir] = "contrib"

projects[hierarchical_select][version] = "3.0-alpha5"
projects[hierarchical_select][subdir] = "contrib"

projects[imce][version] = "1.5"
projects[imce][subdir] = "contrib"

projects[libraries][version] = "1.0"
projects[libraries][subdir] = "contrib"

projects[nodereference_url][version] = "1.12"
projects[nodereference_url][subdir] = "contrib"

projects[references][version] = "2.0"
projects[references][subdir] = "contrib"

projects[rotary_projects_membership][download][type] = "git"
projects[rotary_projects_membership][download][url] = "https://github.com/dwork/image_gallery.git"
projects[rotary_projects_membership][subdir] = "contrib"
projects[rotary_projects_membership][type] = "module"
projects[rotary_projects_membership][version] = "1.0-beta1"

projects[views_fluid_grid][version] = "3.0"
projects[views_fluid_grid][subdir] = "contrib"

projects[views_slideshow][version] = "3.0"
projects[views_slideshow][subdir] = "contrib"


